# Generated by Django 5.1.6 on 2025-03-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='luggage_image',
            field=models.ImageField(default='', upload_to='luggage_images'),
        ),
    ]
