# Generated by Django 5.1.6 on 2025-03-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='pet_image',
            field=models.ImageField(upload_to='luggage_images/'),
        ),
    ]
