# Generated by Django 5.1.6 on 2025-03-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_luggage_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luggage',
            old_name='pet_image',
            new_name='luggage_image',
        ),
    ]
