# Generated by Django 5.1.6 on 2025-03-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_pet_image_luggage_luggage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='luggage_image',
            field=models.ImageField(upload_to='luggage_images'),
        ),
    ]
