# Generated by Django 5.1.6 on 2025-03-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_luggage_luggage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luggage',
            old_name='luggage_image',
            new_name='luggage_images',
        ),
    ]
