# Generated by Django 5.1.6 on 2025-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_luggage_image_luggage_luggage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='luggage_images',
            field=models.ImageField(upload_to='luggage_images/'),
        ),
    ]
