# Generated by Django 5.1.6 on 2025-03-24 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_pet_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
