# Generated by Django 5.1.6 on 2025-03-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_luggage_luggage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pet',
            new_name='product',
        ),
    ]
